import type { Metadata } from 'next';
import ClientThemeProvider from './components/ClientThemeProvider';

export const metadata: Metadata = {
	title: 'NOXU Solutions',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body>
				<ClientThemeProvider>{children}</ClientThemeProvider>
			</body>
		</html>
	);
}
